### PR TITLE
Experiment with threadgroup instead of simd

### LINKED ISSUE #1: Weird Artifacts
Hey! you might already know about this, but I thought I'd still post it just it case it might be helpful. I'm running `piet-metal` on a 2016 MBP with a Radeon Pro 450. It works, but the SVG tiger has *a lot* of artefacts:

Screenshot 2019-05-09 at 08 53 27

I thought it might be integrated chip so I used gfx-status to enforce the discrete GPU and ran it again. That didn't change it though as piet properly automatically uses the discrete device.

Screenshot 2019-05-09 at 08 54 05

Is this expected behaviour? Can I submit any other system info to help out? Great project, looking forward to where this is going!

### PR DESCRIPTION
**Pull request by raphlinus**
Don't use simd, use atomic in threadgroups instead.

This is a performance regression around 10%, but might be more robust.

Fixes #1 (I hope)

### CODE REVIEW

**Comment by terhechte** [comment]
Hey! I just tried this on my Macbook Pro 15" 2016 and it runs fine. The Tiger is displayed beautifully.

**Comment by malthe** [comment]
This shows beautifully for me too on an AMD Radeon™ RX 570.

**Comment by pftbest** [comment]
With this PR I was able to run the code on 2015 MBP with integrated graphics.
The only thing I had to fix was to move one assignment out of the `if` statement.
```diff
@@ -573,20 +573,22 @@ renderKernel(texture2d<half, access::write> outTexture [[texture(0)]],
                 float2 end = fill->end - xy;
                 float2 window = saturate(float2(start.y, end.y));
                 // maybe should be an epsilon test for better numerical stability
+                half delta = 0;
                 if (window.x != window.y) {
                     float2 t = (window - start.y) / (end.y - start.y);
                     float2 xs = mix(float2(start.x), float2(end.x), t);
                     // This fudge factor might be inadequate when xmax is large, could
                     // happen with small slopes.
                     float xmin = min(min(xs.x, xs.y), 1.0) - 1e-6;
                     float xmax = max(xs.x, xs.y);
                     float b = min(xmax, 1.0);
                     float c = max(b, 0.0);
                     float d = max(xmin, 0.0);
                     float area = (b + 0.5 * (d * d - c * c) - xmin) / (xmax - xmin);
                     // TODO: evaluate accuracy loss from more use of half
-                    signedArea += half(area * (window.x - window.y));
+                    delta = half(area * (window.x - window.y));
                 }
+                signedArea += delta;
                 break;
             }
             case CMD_FILL_EDGE: {
```

**Comment by raphlinus** [comment]
@pftbest Sorry for taking so long to follow up. I'm not seeing why moving the `+=` out of the `if` is important in the above code; it looks pretty much the same to me. Do you have any insight what motivated the change and why it's important?

**Comment by pftbest** [comment]
@raphlinus Without this change the MTLCompilerService was crashing in background. I was able to get around the crash by simplifying this expression. But it seems this hack is not needed anymore, I just tested the code on 10.14.6 mojave and it works fine without it.

**Comment by raphlinus** [comment]
I'm merging this and will keep going with a threadgroup based approach for a while, as it's less fiddly than SIMD. In particular, it's not sensitive to SIMD width changing because of the complexity (likely register usage) of the kernel.

**Pull request merged**
